CREATE TABLE [User] (
  UserId INT PRIMARY KEY IDENTITY,
  FirstName VARCHAR(255),
  LastName VARCHAR(255),
  Username VARCHAR(255) UNIQUE NOT NULL,
  PasswordHash VARCHAR(64) NOT NULL,
  Email VARCHAR(255) UNIQUE NOT NULL,
  UserType INT NOT NULL
);